### ISSUE TITLE
game crashes on deconstruct one spacefarer module

### ISSUE THREAD

**Issue by gaksaj** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#24]
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9872945/Player.log)

**Comment by Sgt-Imalas** [comment]
this is a base game bug that is currently in the works of being fixed by klei:
for now, you can prevent that by deconstructing all storage bins and fridges inside

https://forums.kleientertainment.com/klei-bug-tracker/oni/large-solid-oxidizer-tank-has-missing-refresh-triggers-r37405/
https://forums.kleientertainment.com/klei-bug-tracker/oni_so/game-crash-after-destroying-solo-spacefarer-nosecone-repeatable-cannot-continue-playing-r37396/
https://forums.kleientertainment.com/klei-bug-tracker/oni_so/rocket-deconstruction-crash-r37275/
