### ISSUE TITLE
[RoboRockets] Anti-performance

### ISSUE THREAD

**Issue by MegaJani** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#31]
Hi!
It seems the AI modules absolutely tank performance, I'm talking about going from 75 FPS to 10 (!) with four rockets on 2x game speed (a.k.a. medium).
Do you have any optimization planned?

P.S.: I'm currently using AI nosecones, I remember back when only the brain module was implemented that the performance hit wasn't that big. I don't have brains on my current save yet, might try those to see if it's a universal problem.

**Comment by Sgt-Imalas** [comment]
this sounds extremly weird, since they should be way less performance heavy; got a savegame to share?

**Comment by MegaJani** [comment]
Here you go: https://drive.google.com/drive/folders/1HRu1LQXKvRiDnYrJtMeg6_p3BltPMUZE?usp=share_link
It's a bit loaded with mods, but most should not interfere with the rocket controls.
My only guess would be the cluster mod I used to generate the world itself.

> this sounds extremly weird, since they should be way less performance heavy

Yeah, I remembered them being very smooth.

**Comment by Sgt-Imalas** [comment]
So.. I did some testing and I couldnt reproduce extremly low fps. 
the only time they dipped below 30 was fully zoomed out on the star map, but that thing is a clusterfk performance wise without any mods. 
that being said, I didnt install all mods on the list, so there is likely something else.
where do you get these low fps, everywhere; the starmap, a specific planet?
also what happens to your game performance wise if you self destruct these rockets?
what happens if you deactivate one of the following mods, maybe 1 at a time in that order:
- "Cargo Bay Capacity Ports" (that one was a culprit for an issue on the discord recently)
- "Flight Planning" (affects rockets)
- "Improved Rocket Controls" (affects rockets)
- "Fast Track" (maybe some bugged interaction)

Can you test these and report back, best coupled with a log of the game?

**Comment by MegaJani** [comment]
Fps is low everywhere.
I'm still waiting for the rockets to return for dismantling as of now.

As of the mods, I already uninstalled Flight planning. It wasn't the culprit but I didn't use it anyway.
I thought of Fast Track after writing the last reply, I'm currently testing that one.

**Comment by MegaJani** [comment]
Update:
Destroying the rockets increased fps from 10 to 13 (same game tick speed), all other methods had no effect.
This doesn't change when I disable the mod in addition.

It is also a possibility that something other than the rockets cause the performance drop, like discovering the bigger, outer planets, since the rockets were built around the same time as those happened, or another build, like the Drecko farm and the plumbing for the plants. Although Fast Track takes care of those. I also had no problems with the Hatches who lived there before the Dreckos.
Either way, if that is the case, I'm sorry for bothering you.

**Comment by Sgt-Imalas** [comment]
10->13 definitely has something else be the culprit, most likely just the basic bad performance of the game in late game, coupled with the unusual world generation.
oni is limited by single core performance, the larger the map gets and the more of it is uncovered, the worse it gets. in the dlc, the map is split between all moonlets, it does however exclude the ones that haven't been explored from calculations. normal maps have their asteroid count limited to 8 or even less on the classic start, to limit the amount of total map that is in a save game. your "other cluster" save game has 15(!) planets, do it seems most likely that uncovering those drove your pc to its limits (it can somewhat help culling critters/limit their movement to 1x1 tiles and PHYSICALLY (e.g. locked doors/tiles) disallow dupes to access large unused map areas to cull pathing calculations (these take up 3/4 of the time calculating a frame) although fast track should optimize that a lot already

**Comment by MegaJani** [comment]
Oh wow. 
Yeah, 15 planets is insane, would've been nice to know that beforehand, I expected the usual seven to eight.
Might just jump to a fully new save with the same seed and use the blueprint mod to remake the planets, or just rewrite the worldgen entirely to make them smaller (some of them are even larger than the starting planet) 
I knew about the core-speed and pathing, that's why I found it so strange that those didn't work.
Thanks for your help!
Also, is the Discord server you mentioned the one with the Pip thumbnail? I joined it a while back, just didn't know about the modder section. It might be better to talk there instead of Github. Is there a channel for this kind of conversation?

**Comment by Sgt-Imalas** [comment]
yes, its the one with the pip thumbnail.
there is a modded section, its just mostly hidden until you react to the message in  the #read-first channel.
in your case, changing the worldgen might be your easiest option, since that "only" involves manipulating the cluster.yaml file inside of the othercluster mod folder. drastically reducing planet size or even removing certain planets should yield performance increases
