### ISSUE TITLE
Crash during launch 

### ISSUE THREAD

**Issue by MasterVegito** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#32]
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/10558869/Player.log)

Sometimes, it's very rare, but when you launch the rocket, the game CTD's, but doesn't mark the mod in red font. 

crash occured at 16:50 around.

**Comment by Sgt-Imalas** [comment]
The mod isnt marked because its not related.
the crash is caused by something dupe pathfinding/state updating.
while it could be related to a vanilla bug, the insane spam of "gone to checking the way" highly suggests that you have a mod installed that alters the dupes pathfinding in some way that doesn't have rocket launches (disconnecting of the habitat door connection) handled in its logic

**Comment by MasterVegito** [comment]
I indeed have, now I just need to find out which one it oculd be, thank you.
