### ISSUE TITLE
[BUG]: [Duplicant Stat Selector] A Dup with Innate skill Traits give +4 stat point when we remove it

### ISSUE THREAD

**Issue by WoodyPampa** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#63]
### Description of the bug/crash

Hi, 

First of all, thx for your hard work to maintain this mod updated and for the Mod in general, you did something amazing, thx!

And sorry, I'm aware that with each update there is new issue and bug because Klei is removing tags or change names and stuff like that.
And I think I found an other little issue with Duplicant Stat Selector :/

We both know that in theory, an innate skill cost 4 attribute point when Dups are generated and that it's a game rule.
But, if in the portal there is a Dup who spawned with an Innate skill Traits, if we modify it and remove the innate skill from the Traits, then we received +4 attribute point to spend where we want.

Proof:
https://i.ibb.co/HxK37tB/DSS-bug.jpg

It didn't work if we edit a Dup and give him an innate skill, and then remove it, 
I already Tried many possible combination, with 2 Interests or 3, adding an innate skill, removing it. And then adding a Trait like Tryophobia to give to the dup +4 attribute point, adding the innate skill after that, with or without spending the points.
but in all theses cases, each time it work as intended, so it's not possible to abuse about this.

Well, that all I think, I hope it will not bother you too much, thanks for reading me and good luck for the future. 
And again, Thanks for all your hard work 👍 

### Steps To Reproduce

I think you already catch how to reproduce but I'm still write the Steps To Reproduce:

- In game Portal is refreshing
- Open the Portal
- Look at Dups offered and if one of them have an innate skill or not
- If that's not the case, then refresh the portal (or wait the next one :p) 
- Select the Dup with innate skill and clic on "modify"
- clic to remove the innate skill.

And that it.
But it's doing weird things sometime, with all my test, sometime I earn +3 for ... some reason, when I change an interest before, of swap a trait by an other and things like that.
But at this stage I can't help you more, sorry.

### Player.log

I don't think that it will be useful but if you need it I will send you the file
I don't want to sound pretentious, but I'm not a casual user. 
I'm using Mod Manager, Mod Updater, always read the Mod Page and check potential incompatibility and stuff like that.
I close to never have crash and when I have one it's only because of a game update who is breaking some Mods I use.

**Comment by Sgt-Imalas** [comment]
log is always helpful.

answers questions like "do you use bio inks?"
bio inks can add additional skillpoints on top of the normal ones and I dont remove them.
what does the point composition say on those?
(hover the "interest points to spend" text to get the point composition)
![grafik](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/20609939/844414cb-1e20-42dc-838f-975db1ddcece)

**Comment by WoodyPampa** [comment]
No I'm not using Bio inks or RePrint or DGSM, nothing who can interact with dups traits or skill point.
The only one who could be interfering is ["Stock Bug Fix"](https://steamcommunity.com/sharedfiles/filedetails/?id=1967921388&searchtext=) but I turn off everything about dups to be sure that it's not interfering.

There for the Log and I tell you as soon as I can about the "interest points to spend"
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11869215/Player.log)

**Comment by WoodyPampa** [comment]
![image](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/76798400/981af461-3006-4fc4-a3a9-058f75747ee9)

There what you ask for, I just clic to minus to remove the innate skill, nothing else

**Comment by Sgt-Imalas** [comment]
I managed to reproduce it aswell, it only happens if the amount of positive balance (traits with + interest bonus) is less than the total amount of negative ("skilled" traits) balance at the INITIAL dupe generation, as it accidentally assumes that difference to the minimum value to be caused by an external source.
Example:
dupe with 1 interest -> minimum interest bonus of 7.

positive trait is a Skilled trait (-4 point balance) and there are no negative traits.
here the code (wrongly) assumes, that by having the -4, the value should be 3 (7-4=3), and assumes 4 points of unknown origin to fill up the difference (instead of it simply being the minimum amount of interest bonus such a dupe is guaranteed).

A fix for this is probably rather easy and will be included in the next mod update.
Thanks for reporting this rather hidden bug in my mod :D

**Comment by Sgt-Imalas** [comment]
I managed to reproduce it aswell, it only happens if the amount of positive balance (traits with + interest bonus) is less than the total amount of negative ("skilled" traits) balance at the INITIAL dupe generation, as it accidentally assumes that difference to the minimum value to be caused by an external source.
Example:
dupe with 1 interest -> minimum interest bonus of 7.

positive trait is a Skilled trait (-4 point balance) and there are no negative traits.
here the code (wrongly) assumes, that by having the -4, the value should be 3 (7-4=3), and assumes 4 points of unknown origin to fill up the difference (instead of it simply being the minimum amount of interest bonus such a dupe is guaranteed).

A fix for this is probably rather easy and will be included in the next mod update.
Thanks for finding and reporting this rather hidden bug in my mod :D

**Comment by WoodyPampa** [comment]
Yes, I maybe wasn't clear enough about this point, I was talking about a Dups generated from the portal with an innate skill but what you described is exactly the case I was talking about, it's more clear this way.

Sorry to not be able to explain better ^^'

I'm happy that to be able to help and contribute to your Mod ;)

**Comment by Sgt-Imalas** [comment]
The Bug should now be fixed in 5.0.7

**Comment by WoodyPampa** [comment]
I updated the mod and check and I can tell you that at least for me, I can't reproduce this thing now, No more hidden secret exploit for my Dups to start with more Interests points x)

Thx 👍
