### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by VoidedWinter** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#79]
### Description of the bug/crash

Upon updating to the latest version, the mod crashes ONI before the main menu.  ONI loads correctly when the mod's folder is deleted.

### Steps To Reproduce

Not sure, as it caused failure after update.  I'm on linux if it makes a difference.  Wish I could be more helpful.

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12509384/Player.log)

**Comment by Sgt-Imalas** [comment]
which mod?

**Comment by VoidedWinter** [comment]
Sorry, it's Rocketry Expanded.

**Comment by Sgt-Imalas** [comment]
hmmm.. could you test if verifying game files does anything?

**Comment by VoidedWinter** [comment]
It did nothing.

**Comment by richy-notime** [comment]
it seems i have the same problem. verified game data and even reinstalled the game. unsubscribing this mod lets me start the game again. but i cannot load my savegame without this mod due to another crash. so i cannot play until this bug is fixed...

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12522999/Player.log)

**Comment by Sgt-Imalas** [comment]
that is not related to this issue here at all.
the log also doesnt contain any crashes related to rocketry expanded in any way, it only has a zip extraction exception related to the mod ExtendedBridges

**Comment by richy-notime** [comment]
i have unsubscribed the mod ExtendedBridges and the crash still appears:
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12523137/Player.log)
The last row before the errors (Subscribe to mod ExtendedBridges) is not related to the error it seems. I've played the game many hours with this mod combination. After a break yours was the only one with an update. After that the game is not playable anymore.

**Comment by richy-notime** [comment]
would it be possible to provide me the second last version of this mod, so i can use that and report if it works. like i said, i strongly believe this error is related to your last update. if i can do the testing, you have less work.
im very glad the guys like you take the time and make such amazing mods. thank you man :+1:

**Comment by Sgt-Imalas** [comment]
Both logs dont have rocketry expanded enabled

**Comment by Sgt-Imalas** [comment]
I see... then this might be rooted in the games' faulty update system, it probably tries to unzip the file before it is fully downloaded (the update added 3mb of asset bundles but with the previous branch archived_version the mod was already >50mb)

you can manually download and install the latest version of the mod [here](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/releases/tag/v2.7_RocketryExpanded)

**Comment by VoidedWinter** [comment]
Manual install crashes the game as well.
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12527575/Player.log)
(Just in case this time it's helpful)

**Comment by VoidedWinter** [comment]
Went through the old versions that had a compiled zip file.  None of them work either, but I did get an actual error instead of a crash from 2.5.3
[error253.txt](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12527724/error253.txt)

**Comment by Sgt-Imalas** [comment]
old versions are not expected to work as they are compiled against a different version of the game
the corrupted download thing is solely related to richy (also why it is not very helpful of putting different reports into the same issue...)

**Comment by Sgt-Imalas** [comment]
> Manual install crashes the game as well. [Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12527575/Player.log) (Just in case this time it's helpful)

does this just crash to desktop or does it come with a crash message?

if there is one, can you add it here?

**Comment by Sgt-Imalas** [comment]
according to PeterHan this is a native code crash.

"Linux crashes can often be due to weird driver interactions
I have seen bugs on the forum with that signature caused by a variety of issues, including flatpack issues, graphics drivers, audio drivers, even input drivers"

I also found the same error [here](https://www.reddit.com/r/Oxygennotincluded/comments/w2xlyg/have_you_ever_had_problems_with_oni_mods_on/) and [here](https://steamcommunity.com/sharedfiles/filedetails/comments/2348079481)

**Comment by Sgt-Imalas** [comment]
So the issue probably lies somewhere in a random incompatibility between specific drivers and asset bundle handling (since the update introduced asset bundles for custom unity UI for docking, these are implemented platform specific and so far none of my mods that added these had any issues with linux, so it might be system specific)

for now I made a temp. release that has this asset bundle loading (and with it; rocket docking) disabled, [here](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/releases/tag/RE_without_assetBundles)

**Comment by richy-notime** [comment]
manually extracting the zip and using it as a local mod fixed my issue. sry for not using a new issue thread, as i really thought its the same problem like the OP has/had. thanks for your help :+1:

**Comment by VoidedWinter** [comment]
Sadly, my problem persists.
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12534111/Player.log)

**Comment by Sgt-Imalas** [comment]
Good News; I found the source of this crash - a harmony bug that happens in an edge case situation and on linux only
(and a fix, it will go online soon with a few other fixes)

**Comment by Sgt-Imalas** [comment]
could you test if 2.7.0.5 still crashes for you?

**Comment by VoidedWinter** [comment]
Tested and successful.  Kick-ass.
